/// note_model.dart
///
/// Defines the [NoteModel] data class representing a call note
/// attached to a lead. Each note captures the call outcome, follow-up
/// scheduling, and call duration metadata.

import 'package:cloud_firestore/cloud_firestore.dart';

/// Represents a single call note entry in a lead's timeline.
///
/// Notes are stored as a sub-collection under each lead document
/// in Firestore and contain the outcome tag, optional follow-up date,
/// call duration, and the note text itself.
class NoteModel {
  /// Firestore document ID (empty string for new, unsaved notes).
  final String id;

  /// The body text describing what happened during the call.
  final String text;

  /// Outcome tag selected by the user (e.g., 'Interested', 'Callback').
  final String tag;

  /// ISO date string for the next follow-up, or `null` if not set.
  final String? followUpDate;

  /// ISO date-time string for the next follow-up, or `null` if not set.
  final String? followUpDateTime;

  /// Formatted call duration string (e.g., '2m 30s'), or empty if not tracked.
  final String callDuration;

  /// Formatted timestamp of when this note was created.
  final String createdAt;

  /// Whether this note was auto-generated by the system (e.g., for site visits).
  final bool isAutoLog;

  /// Whether this note's text has been edited after initial creation.
  final bool isEdited;

  /// Server-side creation timestamp for tamper-proof 15-minute edit window.
  final DateTime? serverCreatedAt;

  const NoteModel({
    required this.id,
    required this.text,
    required this.tag,
    this.followUpDate,
    this.followUpDateTime,
    required this.callDuration,
    required this.createdAt,
    this.isAutoLog = false,
    this.isEdited = false,
    this.serverCreatedAt,
  });

  /// Creates a [NoteModel] from a Firestore document snapshot.
  ///
  /// [doc] - The Firestore document containing site visit data.
  /// Falls back to sensible defaults for any missing fields.
  factory NoteModel.fromFirestore(DocumentSnapshot doc) {
    final data = doc.data() as Map<String, dynamic>? ?? {};
    return NoteModel(
      id: doc.id,
      text: data['text'] as String? ?? '',
      tag: data['tag'] as String? ?? '',
      followUpDate: data['followUpDate'] as String?,
      followUpDateTime: data['followUpDateTime'] as String?,
      callDuration: data['callDuration'] as String? ?? '',
      createdAt: _parseCreatedAt(data['createdAt']),
      isAutoLog: data['isAutoLog'] as bool? ?? false,
      isEdited: data['isEdited'] as bool? ?? false,
      serverCreatedAt: _parseServerCreatedAt(data['serverCreatedAt']),
    );
  }

  /// Converts this note model into a Firestore-compatible map.
  ///
  /// Used when saving a new note to the lead's notes sub-collection.
  Map<String, dynamic> toMap() {
    return {
      'text': text,
      'tag': tag,
      'followUpDate': followUpDate,
      'followUpDateTime': followUpDateTime,
      'callDuration': callDuration,
      'createdAt': createdAt,
      'isAutoLog': isAutoLog,
      'isEdited': isEdited,
      // serverCreatedAt is set via FieldValue.serverTimestamp() in the service layer
    };
  }

  /// Parses the `createdAt` field from Firestore, handling both
  /// [Timestamp] and [String] types gracefully.
  static String _parseCreatedAt(dynamic value) {
    if (value is Timestamp) {
      return value.toDate().toIso8601String();
    }
    if (value is String) {
      return value;
    }
    return '';
  }

  /// Parses the `serverCreatedAt` field from Firestore, handling both
  /// [Timestamp] and [String] types.
  static DateTime? _parseServerCreatedAt(dynamic value) {
    if (value is Timestamp) {
      return value.toDate();
    }
    if (value is String && value.isNotEmpty) {
      return DateTime.tryParse(value);
    }
    return null;
  }
}
