// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5D57rXvIeddq-oJynvxxxGd0EGvKpjho',
    appId: '1:948589833895:web:2e3d791e5f05b732cf3582',
    messagingSenderId: '948589833895',
    projectId: 'truassets-crm-akp-web',
    authDomain: 'truassets-crm-akp-web.firebaseapp.com',
    storageBucket: 'truassets-crm-akp-web.firebasestorage.app',
    measurementId: 'G-080YLZNPP5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuaDq6dapFSse3pIzluDeCWQZi98fZbG0',
    appId: '1:948589833895:android:072dc704a4df8f7bcf3582',
    messagingSenderId: '948589833895',
    projectId: 'truassets-crm-akp-web',
    storageBucket: 'truassets-crm-akp-web.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKjHLHu3ozln8TgKj_0j-NLH4l30wRfAM',
    appId: '1:948589833895:ios:bf1a861f3f104671cf3582',
    messagingSenderId: '948589833895',
    projectId: 'truassets-crm-akp-web',
    storageBucket: 'truassets-crm-akp-web.firebasestorage.app',
    iosBundleId: 'com.example.flutterTemplate',
  );
}
